language: php
php:
  - '7.1'
  - '7.2'
  - '7.3'

before_script:
  - curl --version
  - composer install --no-interaction --prefer-source --dev

script:
  - mkdir -p build/logs
  - make test

after_success:
  - travis_retry php vendor/bin/php-coveralls